### ISSUE TITLE
Hardcode IP

### ISSUE THREAD

**Issue by sjorge** [nagug/Jellyfin-Actor-Refresh-Script#1]
https://github.com/nagug/Jellyfin-Actor-Refresh-Script/blob/09c9e63d77060933b81d52e36b38072057613416/jellyfin_actor_refresh.sh#L25

should probably not be hardcoded

**Comment by nagug** [comment]
oversight.. agree. let me fix this

**Comment by nagug** [comment]
Fixed it. could you please confirm if this works

**Comment by sjorge** [comment]
Should be fine on anything with gnu sed.
